name: Check - BackEnd

on:
  push:
    branches:
      - main
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  tests-backend:
    strategy:
      matrix:
        name: [Java21]
        include:
          - name: Java21
            os: ubuntu-latest
            java-version: 21
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: oracle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle Tests
        run: |
          ./gradlew test

      - name: Store Tests Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend tests
          path: |
            **/build/reports/
            **/build/test-results/   

      - name: Execute Gradle build
        run: |       
          ./gradlew build

      - name: Store Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: distribution
          path: |
            **/build/libs

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}