name: Check - BackEnd

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests-backend:
    strategy:
      matrix:
        name: [Java21]
        include:
          - name: Java21
            os: ubuntu-latest
            java-version: 21
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: oracle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle Tests
        run: |
          ./gradlew test
